import {
  AS_TAG,
  fetchReportDoc,
  flattenHtml,
  get,
  listQuarterly6K,
  numsAfter,
  toCompanyFacts as packFacts,
  type FetchFn,
  type FsFiling,
  type Sec6kValues,
} from './sec6k';
import { fetchWithTimeout } from './http';
import type { CompanyFacts } from '../analytics/secFundamentals';

/**
 * TSM 交给 EDGAR 的**季度合并财报 6-K**(主文件名形如 `tsm-fsx20260515x6k.htm`)。
 *
 * 为什么走这条而不是 companyfacts:TSM 是外国发行人,只报 20-F/6-K。它的 companyfacts 里
 * 四个科目在 `ifrs-full` 命名空间下都有,但**期间只有半年(180/181 天)和全年**,
 * 而且最新一期停在 2024-12-31 —— 粒度和时效都不能用。而这些 6-K 里是完整 IFRS 季报,
 * **能回填**(实测 13 份、2023Q1 起)且**含现金流量表**,所以四个科目全拿得到。
 *
 * 产出 CompanyFacts 形状,直接喂给 extractFundamentals —— 差分/去重/TTM/合计全部复用,
 * 下游一行都不用改。金额单位是**千元新台币**(报表原文 In Thousands of New Taiwan Dollars),
 * 这里原样保留,币种差异由面板文案交代(见 currencyOf)。
 *
 * 时效:季后约 45 天(实测 2026-03-31 那期 2026-05-15 交)。要更快的读数看 TWSE 月营收(T+10)。
 */

/** 一份季报 6-K 的定位信息(从 sec6k 转出,方便本模块的调用方只 import 一处)。 */
export type { FsFiling } from './sec6k';

/** 一份报告里抽出的**年初至今累计**四科目(千元新台币)。单季由下游差分还原。 */
export type TsmcYtd = Sec6kValues;

/**
 * 解析一份合并报表。**一律取 YTD 列**,单季交给下游差分 —— 这样三种列结构走同一条路径:
 *  · Q1 报告:利润表两列(本季 / 去年同季),YTD 就是它自己
 *  · Q2/Q3 报告:利润表**四列**(三个月 ×2 + N 个月 ×2),YTD 是第 3 列
 *  · Q4(年报):利润表两列(本年 / 去年),YTD 就是全年
 * 现金流量表三种都只有 YTD 两列(本期 / 去年同期),取第 1 个。
 *
 * ⚠️ 利润表每列占**两个单元格**(金额 + 占营收 %),所以第 c 列的金额在第 2c 个数字上。
 * 这一条踩过:按列号直接索引会取到「去年同季」那一列(实测 Q2 2025 取成 673.5B 而非 1773.0B)。
 */
/**
 * 合并报表的单位表头。**必须确认过才敢乘 1000** —— 下游按「基础货币单位」算,
 * 报表哪天改成百万或元,静默换算就是 1000 倍错误(财报稿那条与 ASML 都有同款守卫,
 * 唯独最主要的这条曾经没有)。
 *
 * ⚠️ 词间分隔要吃 `|`:flattenHtml 把**标签**换成 `|` 而不是空格,所以表头里夹一个 `<b>`、
 * `<br>` 或跨单元格换行,`\s+` 就匹配不上 —— 那会让**每一份** TSM 报表都抛错、整条源硬失败。
 */
const REPORT_UNIT_RE = /Thousands[\s|]+of[\s|]+New[\s|]+Taiwan[\s|]+Dollars/i;

export function parseTsmcReport(html: string): TsmcYtd {
  const txt = flattenHtml(html);

  if (!REPORT_UNIT_RE.test(txt)) {
    throw new Error('TSM 合并报表:没确认到「(In) Thousands of New Taiwan Dollars」表头,拒绝按千元换算');
  }

  // 有「Six/Nine Months Ended」表头 = 期中报告(四列);否则 Q1 或年报(两列)。
  const interim = /For the (Six|Nine) Months Ended/i.test(txt);
  const ytdCell = interim ? 4 : 0; // 第 3 列 → 2*2

  const rev = numsAfter(txt, 'NET REVENUE', ytdCell + 1);
  const cogs = numsAfter(txt, 'COST OF REVENUE', ytdCell + 1);
  const ocf = numsAfter(txt, 'Net cash generated by operating activities', 1);

  // 购置 PP&E 必须锚在「INVESTING ACTIVITIES」之后 —— 处置段里有同名的一行,
  // 而资产负债表/附注里「Property, plant and equipment」出现得更早。
  const invIdx = txt.indexOf('INVESTING ACTIVITIES');
  const capex = invIdx < 0 ? [] : numsAfter(txt, 'Property, plant and equipment', 1, invIdx);

  const pick = (xs: number[], idx: number, what: string): number => {
    const v = xs[idx];
    if (v === undefined || !Number.isFinite(v)) throw new Error(`TSM 合并报表:${what} 没解析出来(列结构可能变了)`);
    return v;
  };

  return {
    revenue: pick(rev, ytdCell, 'NET REVENUE'),
    cogs: pick(cogs, ytdCell, 'COST OF REVENUE'),
    ocf: pick(ocf, 0, '经营活动现金流'),
    capex: Math.abs(pick(capex, 0, '购置不动产厂房设备')), // 报表里是负数(现金流出),存正值
  };
}

// ── CompanyFacts 合成 ─────────────────────────────────────────────────────────

/**
 * 报表原文是**千元**新台币("In Thousands of New Taiwan Dollars"),而下游 deriveSeries 除以
 * 1e6 是按「基础货币单位」算的(companyfacts 给的是元)。不乘这 1000,轴会标着「百万新台币」
 * 而实际是十亿 —— 差三个数量级。踩过一次:FCF TTM 显示 1056 而真值是 1,056,000 百万。
 */
const THOUSANDS_TO_UNITS = 1000;

/** 累计口径(`ytd`):start 填当年 1-1,单季由 toQuarters 相邻相减还原。 */
export const toCompanyFacts = (rows: Array<{ filing: FsFiling; ytd: TsmcYtd }>): CompanyFacts =>
  packFacts(
    rows.map(({ filing, ytd }) => ({ filing, values: ytd })),
    'ytd',
    THOUSANDS_TO_UNITS,
  );

// ── 财报稿(T+16,只有营收与毛利)────────────────────────────────────────────

/**
 * 财报稿 6-K 里那张「consolidated results」小表。**比合并报表早约一个月**
 * (实测申报日 T+16~17 对报表的 T+45),代价是只有利润表顶部几行 —— **没有现金流**,
 * 所以 FCF 还是得等报表。
 *
 * ⚠️ 三件事和报表那条不同,混了就是数量级错误或口径错误:
 *  1. **单位是 NT$ million**(报表是 thousand)。相差 1000 倍。
 *  2. 值是**单季**,不是年初至今累计 —— 直接当单季行落库,不进差分。
 *  3. 数字**未经会计师核阅、未经董事会通过**(原文 "figures have not been approved by
 *     Board of Directors")。报表到了会按 filed 更大覆盖它,差异由 job 比对报警。
 *
 * 给的是毛利(Gross profit)而不是成本,故 cogs = 营收 − 毛利。
 */
export type TsmcRelease = { periodEnd: string; revenueM: number; cogsM: number };

const RELEASE_UNIT_RE = /\(Unit[^)]*NT\$\s*million/i;

export function parseEarningsRelease(html: string, periodEnd: string): TsmcRelease {
  const txt = flattenHtml(html);

  // 单位必须自己确认过才敢用 —— 这张表若哪天改成千元,静默换算就是 1000 倍错误。
  // 这个表头同时当**表格锚点**:文里前半段是散文与下季指引,「Gross profit」会先撞上
  // 「Gross profit margin is expected to be between 65% and 67%」。实测踩过,算出 cogs = 0。
  const unitAt = txt.search(RELEASE_UNIT_RE);
  if (unitAt < 0) throw new Error('TSM 财报稿:没确认到「Unit: NT$ million」表头,拒绝按百万换算');

  const table = txt.slice(unitAt);
  const rev = numsAfter(table, 'Net sales', 1);
  const gross = numsAfter(table, 'Gross profit', 1);
  if (rev[0] === undefined || gross[0] === undefined) throw new Error('TSM 财报稿:Net sales / Gross profit 没解析出来');
  // 毛利不可能 >= 营收;相等就说明两个标签命中了同一格(正是上面那个坑的症状)。
  if (gross[0] >= rev[0]) throw new Error(`TSM 财报稿:毛利(${gross[0]})不小于营收(${rev[0]}),解析对错了行`);

  return { periodEnd, revenueM: rev[0], cogsM: rev[0] - gross[0] };
}

const MILLIONS_TO_UNITS = 1_000_000;

/**
 * 财报稿 → **直接单季行**(start 是本季初)。下游的「直接单季行优先于差分」会自然接住。
 * 只有营收与成本 —— 财报稿里没有现金流,FCF 仍得等合并报表。
 */
export function releaseToCompanyFacts(rows: Array<{ filing: FsFiling; rel: TsmcRelease }>): CompanyFacts {
  // ocf/capex 填 0 只是为了套用共享的打包函数,随后把这两个 tag 摘掉 —— 留着会被当成
  // 「本季经营现金流为零」,那是个会静默污染 FCF 的假值。
  // 注:这里通常只有 1~2 期,起始日会退回「期末 − 91 天」,对「是不是一个季度」的判定足够。
  const full = packFacts(
    rows.map(({ filing, rel }) => ({
      filing,
      values: { revenue: rel.revenueM, cogs: rel.cogsM, ocf: 0, capex: 0 },
    })),
    'quarter',
    MILLIONS_TO_UNITS,
  );
  const gaap = full.facts!['us-gaap']!;

  return {
    facts: { 'us-gaap': { [AS_TAG.revenue]: gaap[AS_TAG.revenue]!, [AS_TAG.cogs]: gaap[AS_TAG.cogs]! } },
  };
}

// ── 抓取 ──────────────────────────────────────────────────────────────────────

/** 报表那份 6-K 的封面名前缀。月营收 `tsm-revenue*`、月度例行 `tsm-monthend*` 都不会混进来。 */
const TSM_FS_DOC = /^tsm-fs/i;
/** 财报稿封面名。 */
const TSM_RELEASE_DOC = /^tsm-\d{8}x6k\.htm$/i;
/** 报表目录里要排除的:6-K 封面与母公司单独报表(uncons/standalone,口径不同)。 */
const NOT_THE_REPORT = /^tsm-fs|standalone|uncons/i;

export function createTsmcFetcher(doFetch: FetchFn = fetchWithTimeout) {
  return {
    listFsFilings: (cik: string): Promise<FsFiling[]> => listQuarterly6K(cik, TSM_FS_DOC, doFetch),

    fetchReport: async (cik: string, accn: string): Promise<string> =>
      (await fetchReportDoc(cik, accn, NOT_THE_REPORT, doFetch)).html,

    listEarningsReleases: (cik: string): Promise<FsFiling[]> => listQuarterly6K(cik, TSM_RELEASE_DOC, doFetch),

    /**
     * 财报稿里那份 EX-99.1 正文。附件名实测是 `a{季}q{年}e_withguidancexfinal.htm`
     * (跨 6 个季度一致),但仍留内容兜底:按名字挑不中就在其余 htm 里找含那张表的。
     * 这里不能用「取最大」那招 —— 财报稿目录里最大的 htm 是投资者演示,不是那张表。
     */
    async fetchRelease(cik: string, accn: string): Promise<string> {
      const dir = `https://www.sec.gov/Archives/edgar/data/${Number(cik)}/${accn.replace(/-/g, '')}`;
      const idx = (await (await get(`${dir}/index.json`, doFetch)).json()) as {
        directory?: { item?: Array<{ name?: string }> };
      };

      const htms = (idx.directory?.item ?? [])
        .map((i) => i.name ?? '')
        .filter((n) => /\.htm$/i.test(n) && !/index/i.test(n) && !/^tsm-/i.test(n));
      const ordered = [...htms.filter((n) => /^a\dq\d\de/i.test(n)), ...htms.filter((n) => !/^a\dq\d\de/i.test(n))];

      for (const name of ordered) {
        const html = await (await get(`${dir}/${name}`, doFetch)).text();
        if (/Net sales/i.test(html) && /Gross profit/i.test(html)) return html;
      }
      throw new Error(`TSM 财报稿 ${accn}: 没有一份附件含「Net sales / Gross profit」那张表`);
    },
  };
}
