import { fetchWithTimeout } from './http';
import type { CompanyFacts, FactRow } from '../analytics/secFundamentals';

/**
 * TSM 交给 EDGAR 的**季度合并财报 6-K**(主文件名形如 `tsm-fsx20260515x6k.htm`)。
 *
 * 为什么走这条而不是 companyfacts:TSM 是外国发行人,只报 20-F/6-K。它的 companyfacts 里
 * 四个科目在 `ifrs-full` 命名空间下都有,但**期间只有半年(180/181 天)和全年**,
 * 而且最新一期停在 2024-12-31 —— 粒度和时效都不能用。而这些 6-K 里是完整 IFRS 季报,
 * **能回填**(实测 13 份、2023Q1 起)且**含现金流量表**,所以四个科目全拿得到。
 *
 * 产出 CompanyFacts 形状,直接喂给 extractFundamentals —— 差分/去重/TTM/合计全部复用,
 * 下游一行都不用改。金额单位是**千元新台币**(报表原文 In Thousands of New Taiwan Dollars),
 * 这里原样保留,币种差异由面板文案交代(见 currencyOf)。
 *
 * 时效:季后约 45 天(实测 2026-03-31 那期 2026-05-15 交)。要更快的读数看 TWSE 月营收(T+10)。
 */

const ARCHIVES = 'https://www.sec.gov/Archives/edgar/data';

function userAgent(): string {
  const ua = process.env.SEC_USER_AGENT;
  if (!ua) throw new Error('SEC_USER_AGENT is required (格式:「应用名 邮箱」,见 .env.example)');

  return ua;
}

type FetchFn = (url: string, init?: RequestInit, timeoutMs?: number) => Promise<Response>;

// 合并报表有 4MB 级,默认 15s 在慢网下会临界超时。
const REPORT_TIMEOUT_MS = 60_000;

async function get(url: string, doFetch: FetchFn, timeoutMs?: number): Promise<Response> {
  const res = await doFetch(url, { headers: { 'User-Agent': userAgent(), Accept: '*/*' } }, timeoutMs);
  if (!res.ok) throw new Error(`SEC request failed: ${res.status} ${url}`);

  return res;
}

type Submissions = {
  filings?: {
    recent?: {
      form?: string[];
      filingDate?: string[];
      reportDate?: string[];
      accessionNumber?: string[];
      primaryDocument?: string[];
    };
  };
};

/** 一份季报 6-K 的定位信息。periodEnd 直接取 submissions 的 reportDate —— 不用从正文猜期间。 */
export type FsFiling = { accn: string; filed: string; periodEnd: string };

type DirIndex = { directory?: { item?: Array<{ name?: string; size?: number | string }> } };

// ── 解析 ──────────────────────────────────────────────────────────────────────

/** HTML → 以 `|` 保留单元格边界的扁平文本。表格结构全靠这些竖线定位。 */
export const flattenHtml = (html: string): string =>
  html
    .replace(/<[^>]+>/g, '|')
    .replace(/&nbsp;|&#160;/g, ' ')
    .replace(/&#\d+;/g, ' ')
    .replace(/\|+/g, '|')
    .replace(/[ \t\r\n]+/g, ' ');

/**
 * 一个行标签和它的第一个数字之间最多隔几个单元格。表格里通常是 `标签|$|数字`(隔 1~2 格),
 * 留 8 格余量。**这个上限是必需的守卫**:没有它,标签匹配到散文时会一路扫到下一张表,
 * 把别人的数字当成自己的 —— 实测踩过:「Gross profit」先命中指引句
 * 「Gross profit margin is expected to be between 65% and 67%」,然后扫到表格里 Net sales 的
 * 1,270,381,算出 cogs = 0。
 */
const MAX_CELLS_TO_FIRST_NUMBER = 8;

/**
 * 从某个行标签起,顺序取前 n 个「数字单元格」的值。
 * 负号有**两种写法**,都得吃:`(350,762,799)` 与 `(628,052,531|)`(右括号被拆到下一格)。
 */
function numsAfter(txt: string, label: string, n: number, from = 0): number[] {
  const i = txt.indexOf(label, from);
  if (i < 0) return [];

  const cells = txt.slice(i + label.length, i + label.length + 1500).split('|');
  const out: number[] = [];
  for (let k = 0; k < cells.length && out.length < n; k++) {
    const c = cells[k]!.trim();
    if (!/^\(?[\d,]+\)?$/.test(c) || !/\d/.test(c)) continue;
    // 第一个数字离标签太远 = 这不是那一行,是标签撞进了散文里。宁可空着让上层抛。
    if (out.length === 0 && k > MAX_CELLS_TO_FIRST_NUMBER) return [];

    const neg = c.startsWith('(') || cells[k + 1]?.trim() === ')';
    out.push((neg ? -1 : 1) * Number(c.replace(/[(),]/g, '')));
  }
  return out;
}

/** 一份报告里抽出的**年初至今累计**四科目(千元新台币)。单季由 job 差分还原。 */
export type TsmcYtd = { revenue: number; cogs: number; ocf: number; capex: number };

/**
 * 解析一份合并报表。**一律取 YTD 列**,单季交给下游差分 —— 这样三种列结构走同一条路径:
 *  · Q1 报告:利润表两列(本季 / 去年同季),YTD 就是它自己
 *  · Q2/Q3 报告:利润表**四列**(三个月 ×2 + N 个月 ×2),YTD 是第 3 列
 *  · Q4(年报):利润表两列(本年 / 去年),YTD 就是全年
 * 现金流量表三种都只有 YTD 两列(本期 / 去年同期),取第 1 个。
 *
 * ⚠️ 利润表每列占**两个单元格**(金额 + 占营收 %),所以第 c 列的金额在第 2c 个数字上。
 * 这一条踩过:按列号直接索引会取到「去年同季」那一列(实测 Q2 2025 取成 673.5B 而非 1773.0B)。
 */
export function parseTsmcReport(html: string): TsmcYtd {
  const txt = flattenHtml(html);

  // 有「Six/Nine Months Ended」表头 = 期中报告(四列);否则 Q1 或年报(两列)。
  const interim = /For the (Six|Nine) Months Ended/i.test(txt);
  const ytdCell = interim ? 4 : 0; // 第 3 列 → 2*2

  const rev = numsAfter(txt, 'NET REVENUE', ytdCell + 1);
  const cogs = numsAfter(txt, 'COST OF REVENUE', ytdCell + 1);
  const ocf = numsAfter(txt, 'Net cash generated by operating activities', 1);

  // 购置 PP&E 必须锚在「INVESTING ACTIVITIES」之后 —— 处置段里有同名的一行,
  // 而资产负债表/附注里「Property, plant and equipment」出现得更早。
  const invIdx = txt.indexOf('INVESTING ACTIVITIES');
  const capex = invIdx < 0 ? [] : numsAfter(txt, 'Property, plant and equipment', 1, invIdx);

  const pick = (xs: number[], idx: number, what: string): number => {
    const v = xs[idx];
    if (v === undefined || !Number.isFinite(v)) throw new Error(`TSM 合并报表:${what} 没解析出来(列结构可能变了)`);
    return v;
  };

  return {
    revenue: pick(rev, ytdCell, 'NET REVENUE'),
    cogs: pick(cogs, ytdCell, 'COST OF REVENUE'),
    ocf: pick(ocf, 0, '经营活动现金流'),
    capex: Math.abs(pick(capex, 0, '购置不动产厂房设备')), // 报表里是负数(现金流出),存正值
  };
}

// ── CompanyFacts 合成 ─────────────────────────────────────────────────────────

/**
 * 借用 us-gaap 的 tag 名,让这些行能走 extractFundamentals 那条链。
 * **不是说 TSM 报的是 us-gaap** —— 它是 IFRS。这里只是复用下游的科目映射,
 * 落库后 `tag_used` 会显示这几个名字,溯源要看同行的 accn(指向那份 6-K)。
 */
const AS_TAG = {
  revenue: 'Revenues',
  cogs: 'CostOfRevenue',
  ocf: 'NetCashProvidedByUsedInOperatingActivities',
  capex: 'PaymentsToAcquirePropertyPlantAndEquipment',
} as const;

/** 累计期的起点 = 当年 1 月 1 日(TSM 财年 = 日历年)。差分靠「同 start 分组」,故必须一致。 */
const yearStart = (periodEnd: string) => `${periodEnd.slice(0, 4)}-01-01`;

/**
 * 报表原文是**千元**新台币("In Thousands of New Taiwan Dollars"),而下游 deriveSeries 除以
 * 1e6 是按「基础货币单位」算的(companyfacts 给的是元)。不乘这 1000,轴会标着「百万新台币」
 * 而实际是十亿 —— 差三个数量级。踩过一次:FCF TTM 显示 1056 而真值是 1,056,000 百万。
 */
const THOUSANDS_TO_UNITS = 1000;

export function toCompanyFacts(rows: Array<{ filing: FsFiling; ytd: TsmcYtd }>): CompanyFacts {
  const entries = Object.entries(AS_TAG).map(([concept, tag]) => {
    const usd: FactRow[] = rows.map(({ filing, ytd }) => ({
      start: yearStart(filing.periodEnd),
      end: filing.periodEnd,
      val: ytd[concept as keyof TsmcYtd] * THOUSANDS_TO_UNITS,
      accn: filing.accn,
      // 6-K 不是定期报告,而 periodsForTag 只收 10-Q/10-K —— 标成 10-Q 让它进得去。
      // 这是**刻意的伪装**:TSM 的季报在功能上等同 10-Q,只是外国发行人用 6-K 交。
      form: '10-Q',
      filed: filing.filed,
    }));

    return [tag, { units: { USD: usd } }] as const;
  });

  return { facts: { 'us-gaap': Object.fromEntries(entries) } };
}

// ── 财报稿(T+16,只有营收与毛利)────────────────────────────────────────────

/**
 * 财报稿 6-K 里那张「consolidated results」小表。**比合并报表早约一个月**
 * (实测申报日 T+16~17 对报表的 T+45),代价是只有利润表顶部几行 —— **没有现金流**,
 * 所以 FCF 还是得等报表。
 *
 * ⚠️ 三件事和报表那条不同,混了就是数量级错误或口径错误:
 *  1. **单位是 NT$ million**(报表是 thousand)。相差 1000 倍。
 *  2. 值是**单季**,不是年初至今累计 —— 直接当单季行落库,不进差分。
 *  3. 数字**未经会计师核阅、未经董事会通过**(原文 "figures have not been approved by
 *     Board of Directors")。报表到了会按 filed 更大覆盖它,差异由 job 比对报警。
 *
 * 给的是毛利(Gross profit)而不是成本,故 cogs = 营收 − 毛利。
 */
export type TsmcRelease = { periodEnd: string; revenueM: number; cogsM: number };

const RELEASE_UNIT_RE = /\(Unit[^)]*NT\$\s*million/i;

export function parseEarningsRelease(html: string, periodEnd: string): TsmcRelease {
  const txt = flattenHtml(html);

  // 单位必须自己确认过才敢用 —— 这张表若哪天改成千元,静默换算就是 1000 倍错误。
  // 这个表头同时当**表格锚点**:文里前半段是散文与下季指引,「Gross profit」会先撞上
  // 「Gross profit margin is expected to be between 65% and 67%」。实测踩过,算出 cogs = 0。
  const unitAt = txt.search(RELEASE_UNIT_RE);
  if (unitAt < 0) throw new Error('TSM 财报稿:没确认到「Unit: NT$ million」表头,拒绝按百万换算');

  const table = txt.slice(unitAt);
  const rev = numsAfter(table, 'Net sales', 1);
  const gross = numsAfter(table, 'Gross profit', 1);
  if (rev[0] === undefined || gross[0] === undefined) throw new Error('TSM 财报稿:Net sales / Gross profit 没解析出来');
  // 毛利不可能 >= 营收;相等就说明两个标签命中了同一格(正是上面那个坑的症状)。
  if (gross[0] >= rev[0]) throw new Error(`TSM 财报稿:毛利(${gross[0]})不小于营收(${rev[0]}),解析对错了行`);

  return { periodEnd, revenueM: rev[0], cogsM: rev[0] - gross[0] };
}

const MILLIONS_TO_UNITS = 1_000_000;

/** 财报稿 → **直接单季行**(start 是本季初)。下游的「直接单季行优先于差分」会自然接住。 */
export function releaseToCompanyFacts(rows: Array<{ filing: FsFiling; rel: TsmcRelease }>): CompanyFacts {
  const quarterStart = (periodEnd: string) => {
    const [y, m] = periodEnd.split('-').map(Number);
    return `${y}-${String(m! - 2).padStart(2, '0')}-01`; // 06-30 → 04-01
  };

  const mk = (concept: 'revenueM' | 'cogsM'): FactRow[] =>
    rows.map(({ filing, rel }) => ({
      start: quarterStart(rel.periodEnd),
      end: rel.periodEnd,
      val: rel[concept] * MILLIONS_TO_UNITS,
      accn: filing.accn,
      form: '10-Q', // 同 toCompanyFacts:为了进 periodsForTag 的定期报告白名单
      filed: filing.filed,
    }));

  return {
    facts: {
      'us-gaap': {
        [AS_TAG.revenue]: { units: { USD: mk('revenueM') } },
        [AS_TAG.cogs]: { units: { USD: mk('cogsM') } },
      },
    },
  };
}

// ── 抓取 ──────────────────────────────────────────────────────────────────────

export function createTsmcFetcher(doFetch: FetchFn = fetchWithTimeout) {
  return {
    /** 全部季度财报 6-K,按期末升序。primaryDocument 以 `tsm-fs` 开头是它们的稳定标志。 */
    async listFsFilings(cik: string): Promise<FsFiling[]> {
      const body = (await (
        await get(`https://data.sec.gov/submissions/CIK${cik.padStart(10, '0')}.json`, doFetch)
      ).json()) as Submissions;
      const {
        form = [],
        filingDate = [],
        reportDate = [],
        accessionNumber = [],
        primaryDocument = [],
      } = body.filings?.recent ?? {};

      return primaryDocument
        .flatMap((doc, i) =>
          form[i] === '6-K' && /^tsm-fs/i.test(doc ?? '') && reportDate[i] && accessionNumber[i] && filingDate[i]
            ? [{ accn: accessionNumber[i]!, filed: filingDate[i]!, periodEnd: reportDate[i]! }]
            : [],
        )
        .sort((a, b) => a.periodEnd.localeCompare(b.periodEnd));
    },

    /**
     * 取某份 6-K 里的合并报表正文。
     *
     * **不按文件名认**:命名不稳定(实测出现过 `tsmc2023q1.htm`、`a0515.htm`、拼错的
     * `consolidatd`、以及 workiva 前缀)。改成「排除 6-K 封面与母公司单独报表后取最大那份」——
     * 合并报表 4MB 级,封面十几 KB,量级差三个数量级。
     */
    async fetchReport(cik: string, accn: string): Promise<string> {
      const dir = `${ARCHIVES}/${Number(cik)}/${accn.replace(/-/g, '')}`;
      const idx = (await (await get(`${dir}/index.json`, doFetch)).json()) as DirIndex;

      const doc = (idx.directory?.item ?? [])
        .filter(
          (i) =>
            /\.htm$/i.test(i.name ?? '') &&
            !/^tsm-fs/i.test(i.name ?? '') &&
            !/index/i.test(i.name ?? '') &&
            !/standalone|uncons/i.test(i.name ?? ''),
        )
        .sort((a, b) => Number(b.size ?? 0) - Number(a.size ?? 0))[0];
      if (!doc?.name) throw new Error(`TSM 6-K ${accn}: 目录里没有合并报表正文`);

      return (await get(`${dir}/${doc.name}`, doFetch, REPORT_TIMEOUT_MS)).text();
    },

    /**
     * 财报稿 6-K,按期末升序。封面名形如 `tsm-20260716x6k.htm` —— 这个模式是稳定的,
     * 而月营收(`tsm-revenue*`)、月度例行(`tsm-monthend*`)、报表(`tsm-fs*`)都另有前缀,
     * 不会混进来。
     */
    async listEarningsReleases(cik: string): Promise<FsFiling[]> {
      const body = (await (
        await get(`https://data.sec.gov/submissions/CIK${cik.padStart(10, '0')}.json`, doFetch)
      ).json()) as Submissions;
      const {
        form = [],
        filingDate = [],
        reportDate = [],
        accessionNumber = [],
        primaryDocument = [],
      } = body.filings?.recent ?? {};

      return primaryDocument
        .flatMap((doc, i) =>
          form[i] === '6-K' &&
          /^tsm-\d{8}x6k\.htm$/i.test(doc ?? '') &&
          reportDate[i] &&
          accessionNumber[i] &&
          filingDate[i]
            ? [{ accn: accessionNumber[i]!, filed: filingDate[i]!, periodEnd: reportDate[i]! }]
            : [],
        )
        .sort((a, b) => a.periodEnd.localeCompare(b.periodEnd));
    },

    /**
     * 财报稿里那份 EX-99.1 正文。附件名实测是 `a{季}q{年}e_withguidancexfinal.htm`
     * (跨 6 个季度一致),但仍留内容兜底:按名字挑不中就在其余 htm 里找含那张表的。
     */
    async fetchRelease(cik: string, accn: string): Promise<string> {
      const dir = `${ARCHIVES}/${Number(cik)}/${accn.replace(/-/g, '')}`;
      const idx = (await (await get(`${dir}/index.json`, doFetch)).json()) as DirIndex;

      const htms = (idx.directory?.item ?? [])
        .map((i) => i.name ?? '')
        .filter((n) => /\.htm$/i.test(n) && !/index/i.test(n) && !/^tsm-/i.test(n));
      // 命名模式优先,其余按体积从大到小试 —— 那张表在 EX-99.1 里,不在 6-K 封面。
      const ordered = [...htms.filter((n) => /^a\dq\d\de/i.test(n)), ...htms.filter((n) => !/^a\dq\d\de/i.test(n))];

      for (const name of ordered) {
        const html = await (await get(`${dir}/${name}`, doFetch)).text();
        if (/Net sales/i.test(html) && /Gross profit/i.test(html)) return html;
      }
      throw new Error(`TSM 财报稿 ${accn}: 没有一份附件含「Net sales / Gross profit」那张表`);
    },
  };
}
