import { describe, expect, test } from 'bun:test';
import { parseTsmcReport, toCompanyFacts, type FsFiling } from './tsmcReports';
import { extractFundamentals } from '../analytics/secFundamentals';

// 三种列结构各造一份最小片段。真实报表 4MB,这里只留决定解析对错的那几行。
const cell = (xs: (string | number)[]) => xs.map(String).join('|');

/** Q1 / 年报:利润表两列(本期 + 去年同期),每列「金额 + %」两格。 */
const twoCol = (rev: number, cogs: number, ocf: number, capex: number) =>
  `<p>CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME</p><table><tr><td>2026</td><td>2025</td></tr>` +
  `<tr><td>NET REVENUE (Notes 20)</td><td>$</td><td>${rev.toLocaleString('en-US')}</td><td>100</td>` +
  `<td>$</td><td>839,253,664</td><td>100</td></tr>` +
  `<tr><td>COST OF REVENUE (Notes 12)</td><td>${cogs.toLocaleString('en-US')}</td><td>34</td>` +
  `<td>345,858,588</td><td>41</td></tr></table>` +
  `<p>CONSOLIDATED STATEMENTS OF CASH FLOWS</p><table>` +
  `<tr><td>Net cash generated by operating activities</td><td>${ocf.toLocaleString('en-US')}</td><td>625,573,672</td></tr>` +
  `<tr><td>INVESTING ACTIVITIES</td></tr><tr><td>Acquisitions of</td></tr>` +
  `<tr><td>Property, plant and equipment</td><td>(${capex.toLocaleString('en-US')})</td><td>(330,826,730)</td></tr>` +
  `<tr><td>Proceeds from disposal or redemption of</td></tr>` +
  `<tr><td>Property, plant and equipment </td><td>1,812,754</td><td>127,764</td></tr></table>`;

/** Q2/Q3:利润表**四列**(三个月 ×2 + N 个月 ×2),YTD 是第 3 列。 */
const fourCol = (q: number, ytd: number, cogsQ: number, cogsYtd: number) =>
  `<p>CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME</p><table>` +
  `<tr><td>For the Three Months Ended June 30</td><td>For the Six Months Ended June 30</td></tr>` +
  `<tr><td>NET REVENUE (Notes 20)</td><td>$</td><td>${q.toLocaleString('en-US')}</td><td>100</td>` +
  `<td>$</td><td>673,510,177</td><td>100</td><td>$</td><td>${ytd.toLocaleString('en-US')}</td><td>100</td>` +
  `<td>$</td><td>1,266,154,378</td><td>100</td></tr>` +
  `<tr><td>COST OF REVENUE (Notes 12)</td><td>${cogsQ.toLocaleString('en-US')}</td><td>41</td>` +
  `<td>315,385,699</td><td>47</td><td>${cogsYtd.toLocaleString('en-US')}</td><td>41</td>` +
  `<td>593,524,631</td><td>47</td></tr></table>` +
  `<p>CONSOLIDATED STATEMENTS OF CASH FLOWS</p><table><tr><td>Six Months Ended June 30</td></tr>` +
  `<tr><td>Net cash generated by operating activities</td><td>1,122,637,757</td><td>813,979,318</td></tr>` +
  `<tr><td>INVESTING ACTIVITIES</td></tr><tr><td>Acquisitions of</td></tr>` +
  // 负号的第二种写法:右括号被拆到下一个单元格(实测 Q2 2025 的排版)。
  `<tr><td>Property, plant and equipment</td><td>(628,052,531</td><td>)</td><td>(386,979,486</td><td>)</td></tr>` +
  `</table>`;

describe('parseTsmcReport', () => {
  test('两列报告(Q1/年报):取本期那一列', () => {
    // 实测 Q1 2026 的真值。
    expect(parseTsmcReport(twoCol(1_134_103_440, 382_808_019, 698_976_265, 350_762_799))).toEqual({
      revenue: 1_134_103_440,
      cogs: 382_808_019,
      ocf: 698_976_265,
      capex: 350_762_799, // 报表里是负数(流出),存正值
    });
  });

  test('四列报告(Q2/Q3):取 **YTD** 而不是本季 —— 每列占两格,按列号直接索引会取到去年同季', () => {
    // 实测 Q2 2025:本季 933,791,869 / H1 1,773,045,533。取错列会得到 673,510,177(去年同季)。
    const r = parseTsmcReport(fourCol(933_791_869, 1_773_045_533, 386_422_631, 732_281_219));

    expect(r.revenue).toBe(1_773_045_533);
    expect(r.cogs).toBe(732_281_219);
    expect(r.revenue).not.toBe(673_510_177);
  });

  test('负号两种写法都吃:(N) 与 (N|)', () => {
    expect(parseTsmcReport(fourCol(1, 2, 1, 1)).capex).toBe(628_052_531); // 右括号在下一格
    expect(parseTsmcReport(twoCol(1, 1, 1, 350_762_799)).capex).toBe(350_762_799); // 括号在同一格
  });

  test('capex 锚在 INVESTING ACTIVITIES 之后 —— 处置段有同名的一行,取错会拿到 1,812,754', () => {
    expect(parseTsmcReport(twoCol(1, 1, 1, 350_762_799)).capex).not.toBe(1_812_754);
  });

  test('缺行就抛,不静默给 0(0 会被当成真实的「本季没花钱」)', () => {
    expect(() => parseTsmcReport('<p>NET REVENUE</p>')).toThrow(/没解析出来/);
  });
});

describe('toCompanyFacts', () => {
  const filing = (periodEnd: string, accn: string, filed: string): FsFiling => ({ accn, filed, periodEnd });

  test('千元 → 元:不乘 1000,轴会标着百万而实际是十亿', () => {
    const facts = toCompanyFacts([
      { filing: filing('2026-03-31', 'a', '2026-05-15'), ytd: { revenue: 1_134_103_440, cogs: 1, ocf: 1, capex: 1 } },
    ]);

    expect(facts.facts!['us-gaap']!.Revenues!.units!.USD![0]!.val).toBe(1_134_103_440_000);
  });

  test('累计 start 固定为当年 1-1,故差分只在同一年内发生(Q1 的累计即单季)', () => {
    const rows = [
      { filing: filing('2025-12-31', 'y25', '2026-02-26'), ytd: { revenue: 3_809_054_272, cogs: 1, ocf: 1, capex: 1 } },
      { filing: filing('2026-03-31', 'q1', '2026-05-15'), ytd: { revenue: 1_134_103_440, cogs: 1, ocf: 1, capex: 1 } },
    ];
    const out = extractFundamentals('TSM', toCompanyFacts(rows));
    const q1 = out.find((r) => r.periodEnd === '2026-03-31' && r.concept === 'revenue')!;

    // 跨年不相减:2026Q1 = 它自己,不是 1,134 − 3,809。
    expect(q1.value).toBe(1_134_103_440_000);
    expect(q1.accn).toBe('q1'); // 溯源指向那份 6-K
  });

  test('同一年内相邻两期相减还原单季', () => {
    const rows = [
      { filing: filing('2025-03-31', 'q1', '2025-05-15'), ytd: { revenue: 839_253_664, cogs: 1, ocf: 1, capex: 1 } },
      { filing: filing('2025-06-30', 'q2', '2025-08-14'), ytd: { revenue: 1_773_045_533, cogs: 2, ocf: 2, capex: 2 } },
    ];
    const out = extractFundamentals('TSM', toCompanyFacts(rows));
    const q2 = out.find((r) => r.periodEnd === '2025-06-30' && r.concept === 'revenue')!;

    // 实测 Q2 2025 单季营收 933,791,869 千元 = 1,773,045,533 − 839,253,664。
    expect(q2.value).toBe(933_791_869_000);
  });
});
