import { describe, expect, test } from 'bun:test';
import {
  parseEarningsRelease,
  parseTsmcReport,
  releaseToCompanyFacts,
  toCompanyFacts,
  type FsFiling,
} from './tsmcReports';
import { extractFundamentals } from '../analytics/secFundamentals';

// 三种列结构各造一份最小片段。真实报表 4MB,这里只留决定解析对错的那几行。
/** Q1 / 年报:利润表两列(本期 + 去年同期),每列「金额 + %」两格。 */
const twoCol = (rev: number, cogs: number, ocf: number, capex: number) =>
  `<p>CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME</p><table><tr><td>2026</td><td>2025</td></tr>` +
  `<tr><td>NET REVENUE (Notes 20)</td><td>$</td><td>${rev.toLocaleString('en-US')}</td><td>100</td>` +
  `<td>$</td><td>839,253,664</td><td>100</td></tr>` +
  `<tr><td>COST OF REVENUE (Notes 12)</td><td>${cogs.toLocaleString('en-US')}</td><td>34</td>` +
  `<td>345,858,588</td><td>41</td></tr></table>` +
  `<p>CONSOLIDATED STATEMENTS OF CASH FLOWS</p><table>` +
  `<tr><td>Net cash generated by operating activities</td><td>${ocf.toLocaleString('en-US')}</td><td>625,573,672</td></tr>` +
  `<tr><td>INVESTING ACTIVITIES</td></tr><tr><td>Acquisitions of</td></tr>` +
  `<tr><td>Property, plant and equipment</td><td>(${capex.toLocaleString('en-US')})</td><td>(330,826,730)</td></tr>` +
  `<tr><td>Proceeds from disposal or redemption of</td></tr>` +
  `<tr><td>Property, plant and equipment </td><td>1,812,754</td><td>127,764</td></tr></table>`;

/** Q2/Q3:利润表**四列**(三个月 ×2 + N 个月 ×2),YTD 是第 3 列。 */
const fourCol = (q: number, ytd: number, cogsQ: number, cogsYtd: number) =>
  `<p>CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME</p><table>` +
  `<tr><td>For the Three Months Ended June 30</td><td>For the Six Months Ended June 30</td></tr>` +
  `<tr><td>NET REVENUE (Notes 20)</td><td>$</td><td>${q.toLocaleString('en-US')}</td><td>100</td>` +
  `<td>$</td><td>673,510,177</td><td>100</td><td>$</td><td>${ytd.toLocaleString('en-US')}</td><td>100</td>` +
  `<td>$</td><td>1,266,154,378</td><td>100</td></tr>` +
  `<tr><td>COST OF REVENUE (Notes 12)</td><td>${cogsQ.toLocaleString('en-US')}</td><td>41</td>` +
  `<td>315,385,699</td><td>47</td><td>${cogsYtd.toLocaleString('en-US')}</td><td>41</td>` +
  `<td>593,524,631</td><td>47</td></tr></table>` +
  `<p>CONSOLIDATED STATEMENTS OF CASH FLOWS</p><table><tr><td>Six Months Ended June 30</td></tr>` +
  `<tr><td>Net cash generated by operating activities</td><td>1,122,637,757</td><td>813,979,318</td></tr>` +
  `<tr><td>INVESTING ACTIVITIES</td></tr><tr><td>Acquisitions of</td></tr>` +
  // 负号的第二种写法:右括号被拆到下一个单元格(实测 Q2 2025 的排版)。
  `<tr><td>Property, plant and equipment</td><td>(628,052,531</td><td>)</td><td>(386,979,486</td><td>)</td></tr>` +
  `</table>`;

describe('parseTsmcReport', () => {
  test('两列报告(Q1/年报):取本期那一列', () => {
    // 实测 Q1 2026 的真值。
    expect(parseTsmcReport(twoCol(1_134_103_440, 382_808_019, 698_976_265, 350_762_799))).toEqual({
      revenue: 1_134_103_440,
      cogs: 382_808_019,
      ocf: 698_976_265,
      capex: 350_762_799, // 报表里是负数(流出),存正值
    });
  });

  test('四列报告(Q2/Q3):取 **YTD** 而不是本季 —— 每列占两格,按列号直接索引会取到去年同季', () => {
    // 实测 Q2 2025:本季 933,791,869 / H1 1,773,045,533。取错列会得到 673,510,177(去年同季)。
    const r = parseTsmcReport(fourCol(933_791_869, 1_773_045_533, 386_422_631, 732_281_219));

    expect(r.revenue).toBe(1_773_045_533);
    expect(r.cogs).toBe(732_281_219);
    expect(r.revenue).not.toBe(673_510_177);
  });

  test('负号两种写法都吃:(N) 与 (N|)', () => {
    expect(parseTsmcReport(fourCol(1, 2, 1, 1)).capex).toBe(628_052_531); // 右括号在下一格
    expect(parseTsmcReport(twoCol(1, 1, 1, 350_762_799)).capex).toBe(350_762_799); // 括号在同一格
  });

  test('capex 锚在 INVESTING ACTIVITIES 之后 —— 处置段有同名的一行,取错会拿到 1,812,754', () => {
    expect(parseTsmcReport(twoCol(1, 1, 1, 350_762_799)).capex).not.toBe(1_812_754);
  });

  test('缺行就抛,不静默给 0(0 会被当成真实的「本季没花钱」)', () => {
    expect(() => parseTsmcReport('<p>NET REVENUE</p>')).toThrow(/没解析出来/);
  });
});

describe('toCompanyFacts', () => {
  const filing = (periodEnd: string, accn: string, filed: string): FsFiling => ({ accn, filed, periodEnd });

  test('千元 → 元:不乘 1000,轴会标着百万而实际是十亿', () => {
    const facts = toCompanyFacts([
      { filing: filing('2026-03-31', 'a', '2026-05-15'), ytd: { revenue: 1_134_103_440, cogs: 1, ocf: 1, capex: 1 } },
    ]);

    expect(facts.facts!['us-gaap']!.Revenues!.units!.USD![0]!.val).toBe(1_134_103_440_000);
  });

  test('累计 start 固定为当年 1-1,故差分只在同一年内发生(Q1 的累计即单季)', () => {
    const rows = [
      { filing: filing('2025-12-31', 'y25', '2026-02-26'), ytd: { revenue: 3_809_054_272, cogs: 1, ocf: 1, capex: 1 } },
      { filing: filing('2026-03-31', 'q1', '2026-05-15'), ytd: { revenue: 1_134_103_440, cogs: 1, ocf: 1, capex: 1 } },
    ];
    const out = extractFundamentals('TSM', toCompanyFacts(rows));
    const q1 = out.find((r) => r.periodEnd === '2026-03-31' && r.concept === 'revenue')!;

    // 跨年不相减:2026Q1 = 它自己,不是 1,134 − 3,809。
    expect(q1.value).toBe(1_134_103_440_000);
    expect(q1.accn).toBe('q1'); // 溯源指向那份 6-K
  });

  test('同一年内相邻两期相减还原单季', () => {
    const rows = [
      { filing: filing('2025-03-31', 'q1', '2025-05-15'), ytd: { revenue: 839_253_664, cogs: 1, ocf: 1, capex: 1 } },
      { filing: filing('2025-06-30', 'q2', '2025-08-14'), ytd: { revenue: 1_773_045_533, cogs: 2, ocf: 2, capex: 2 } },
    ];
    const out = extractFundamentals('TSM', toCompanyFacts(rows));
    const q2 = out.find((r) => r.periodEnd === '2025-06-30' && r.concept === 'revenue')!;

    // 实测 Q2 2025 单季营收 933,791,869 千元 = 1,773,045,533 − 839,253,664。
    expect(q2.value).toBe(933_791_869_000);
  });
});

// ── 财报稿(T+16)─────────────────────────────────────────────────────────────

/** 财报稿的真实形状:**指引散文在前、表格在后**,而指引里有「Gross profit margin」。 */
const release = (rev: number, gross: number, unit = 'NT$ million') =>
  `<p>TSMC Reports Second Quarter EPS of NT$27.25</p>` +
  `<p>Gross margin for the quarter was 67.7%, operating margin was 60.3%.</p>` +
  // ⚠️ 这句是坑:它在表格之前,且含「Gross profit」。
  `<p>Gross profit margin is expected to be between 65% and 67%</p>` +
  `<p>Operating profit margin is expected to be between 56% and 58%.</p>` +
  `<p>TSMC's 2026 second quarter consolidated results (Unit: ${unit}, except for EPS)</p><table>` +
  `<tr><td>2Q26</td><td>2Q25</td><td>YoY %</td><td>1Q26</td><td>QoQ %</td></tr>` +
  `<tr><td>Net sales</td><td>${rev.toLocaleString('en-US')}</td><td>933,792</td><td>36.0</td><td>1,134,103</td><td>12.0</td></tr>` +
  `<tr><td>Gross profit</td><td>${gross.toLocaleString('en-US')}</td><td>547,369</td><td>57.2</td><td>751,295</td><td>14.5</td></tr>` +
  `<tr><td>Income from operations</td><td>766,603</td><td>463,423</td><td>65.4</td><td>658,966</td><td>16.3</td></tr>` +
  `</table>`;

describe('parseEarningsRelease', () => {
  test('锚在「Unit」表头之后 —— 否则 Gross profit 会命中前面的指引句', () => {
    // 实测踩过:不锚定时 gross 扫到表格里 Net sales 的 1,270,381,算出 cogs = 0。
    const r = parseEarningsRelease(release(1_270_381, 860_311), '2026-06-30');

    expect(r).toEqual({ periodEnd: '2026-06-30', revenueM: 1_270_381, cogsM: 410_070 });
    // 与合并报表交叉验证:410,070 百万 = 报表的 410,070,xxx 千元。
    expect(((r.revenueM - r.cogsM) / r.revenueM) * 100).toBeCloseTo(67.72, 2);
  });

  test('单位不是 million 就抛 —— 静默按百万换算是 1000 倍错误', () => {
    expect(() => parseEarningsRelease(release(1, 0, 'NT$ thousand'), '2026-06-30')).toThrow(/拒绝按百万换算/);
  });

  test('毛利 >= 营收 就抛(两个标签命中同一格的症状)', () => {
    expect(() => parseEarningsRelease(release(1_270_381, 1_270_381), '2026-06-30')).toThrow(/不小于营收/);
  });

  test('只有散文没有表 → 抛,不硬凑出一个数', () => {
    // 两个标签都会扫到后面那个孤立的 999 → 被「毛利不小于营收」拦下。
    // (距离守卫拦不住这一例:整段散文是**一个**单元格,数字反而离得近。两条守卫互补。)
    const prose =
      '<p>(Unit: NT$ million)</p><p>Net sales grew strongly this quarter across all of our leading-edge nodes ' +
      'and advanced packaging services, with particular strength in high performance computing.</p>' +
      '<p>Gross profit also improved.</p><table><tr><td>999</td></tr></table>';
    expect(() => parseEarningsRelease(prose, '2026-06-30')).toThrow();
  });

  test('距离守卫:标签与数字之间隔了 8 个以上非空单元格 → 当作没找到', () => {
    // 空单元格不算距离(flattenHtml 会把连续的 | 折成一个),所以这里用文字单元格制造距离。
    const filler = Array.from({ length: 10 }, (_, i) => `<td>note ${i}</td>`).join('');
    const far =
      `<p>(Unit: NT$ million)</p><table><tr><td>Net sales</td>${filler}<td>1,270,381</td></tr>` +
      '<tr><td>Gross profit</td><td>860,311</td></tr></table>';
    expect(() => parseEarningsRelease(far, '2026-06-30')).toThrow(/没解析出来/);
  });
});

describe('releaseToCompanyFacts', () => {
  const f: FsFiling = { accn: 'rel', filed: '2026-07-16', periodEnd: '2026-06-30' };
  const rel = { periodEnd: '2026-06-30', revenueM: 1_270_381, cogsM: 410_070 };

  test('百万 → 元,且是**直接单季行**(约 91 天跨度),不进 YTD 差分', () => {
    const facts = releaseToCompanyFacts([{ filing: f, rel }]);
    const row = facts.facts!['us-gaap']!.Revenues!.units!.USD![0]!;

    expect(row.val).toBe(1_270_381_000_000);
    expect(row.end).toBe('2026-06-30');
    // start 表达的是「这是一个季度」而非精确季初:只有一期时退回「期末 − 91 天」。
    // 关键是**不能是当年 1-1**(那会被当成 YTD 去差分)。
    expect(row.start).not.toBe('2026-01-01');
    const days = (Date.parse(row.end) - Date.parse(row.start!)) / 86_400_000;
    expect(days).toBeGreaterThan(80);
    expect(days).toBeLessThan(100);
  });

  test('只给营收与成本 —— 现金流不在财报稿里,FCF 仍得等报表', () => {
    const tags = Object.keys(releaseToCompanyFacts([{ filing: f, rel }]).facts!['us-gaap']!);
    expect(tags).toEqual(['Revenues', 'CostOfRevenue']);
  });

  test('落库后单季值直接可用(无需相邻期相减)', () => {
    const out = extractFundamentals('TSM', releaseToCompanyFacts([{ filing: f, rel }]));
    const rev = out.find((r) => r.concept === 'revenue')!;

    expect(rev).toMatchObject({ periodEnd: '2026-06-30', value: 1_270_381_000_000, accn: 'rel' });
  });
});
