import { fetchWithTimeout } from './http';
import type { CompanyFacts, FactRow } from '../analytics/secFundamentals';

/**
 * TSM 交给 EDGAR 的**季度合并财报 6-K**(主文件名形如 `tsm-fsx20260515x6k.htm`)。
 *
 * 为什么走这条而不是 companyfacts:TSM 是外国发行人,只报 20-F/6-K。它的 companyfacts 里
 * 四个科目在 `ifrs-full` 命名空间下都有,但**期间只有半年(180/181 天)和全年**,
 * 而且最新一期停在 2024-12-31 —— 粒度和时效都不能用。而这些 6-K 里是完整 IFRS 季报,
 * **能回填**(实测 13 份、2023Q1 起)且**含现金流量表**,所以四个科目全拿得到。
 *
 * 产出 CompanyFacts 形状,直接喂给 extractFundamentals —— 差分/去重/TTM/合计全部复用,
 * 下游一行都不用改。金额单位是**千元新台币**(报表原文 In Thousands of New Taiwan Dollars),
 * 这里原样保留,币种差异由面板文案交代(见 currencyOf)。
 *
 * 时效:季后约 45 天(实测 2026-03-31 那期 2026-05-15 交)。要更快的读数看 TWSE 月营收(T+10)。
 */

const ARCHIVES = 'https://www.sec.gov/Archives/edgar/data';

function userAgent(): string {
  const ua = process.env.SEC_USER_AGENT;
  if (!ua) throw new Error('SEC_USER_AGENT is required (格式:「应用名 邮箱」,见 .env.example)');

  return ua;
}

type FetchFn = (url: string, init?: RequestInit, timeoutMs?: number) => Promise<Response>;

// 合并报表有 4MB 级,默认 15s 在慢网下会临界超时。
const REPORT_TIMEOUT_MS = 60_000;

async function get(url: string, doFetch: FetchFn, timeoutMs?: number): Promise<Response> {
  const res = await doFetch(url, { headers: { 'User-Agent': userAgent(), Accept: '*/*' } }, timeoutMs);
  if (!res.ok) throw new Error(`SEC request failed: ${res.status} ${url}`);

  return res;
}

type Submissions = {
  filings?: {
    recent?: {
      form?: string[];
      filingDate?: string[];
      reportDate?: string[];
      accessionNumber?: string[];
      primaryDocument?: string[];
    };
  };
};

/** 一份季报 6-K 的定位信息。periodEnd 直接取 submissions 的 reportDate —— 不用从正文猜期间。 */
export type FsFiling = { accn: string; filed: string; periodEnd: string };

type DirIndex = { directory?: { item?: Array<{ name?: string; size?: number | string }> } };

// ── 解析 ──────────────────────────────────────────────────────────────────────

/** HTML → 以 `|` 保留单元格边界的扁平文本。表格结构全靠这些竖线定位。 */
export const flattenHtml = (html: string): string =>
  html
    .replace(/<[^>]+>/g, '|')
    .replace(/&nbsp;|&#160;/g, ' ')
    .replace(/&#\d+;/g, ' ')
    .replace(/\|+/g, '|')
    .replace(/[ \t\r\n]+/g, ' ');

/**
 * 从某个行标签起,顺序取前 n 个「数字单元格」的值。
 * 负号有**两种写法**,都得吃:`(350,762,799)` 与 `(628,052,531|)`(右括号被拆到下一格)。
 */
function numsAfter(txt: string, label: string, n: number, from = 0): number[] {
  const i = txt.indexOf(label, from);
  if (i < 0) return [];

  const cells = txt.slice(i + label.length, i + label.length + 1500).split('|');
  const out: number[] = [];
  for (let k = 0; k < cells.length && out.length < n; k++) {
    const c = cells[k]!.trim();
    if (!/^\(?[\d,]+\)?$/.test(c) || !/\d/.test(c)) continue;

    const neg = c.startsWith('(') || cells[k + 1]?.trim() === ')';
    out.push((neg ? -1 : 1) * Number(c.replace(/[(),]/g, '')));
  }
  return out;
}

/** 一份报告里抽出的**年初至今累计**四科目(千元新台币)。单季由 job 差分还原。 */
export type TsmcYtd = { revenue: number; cogs: number; ocf: number; capex: number };

/**
 * 解析一份合并报表。**一律取 YTD 列**,单季交给下游差分 —— 这样三种列结构走同一条路径:
 *  · Q1 报告:利润表两列(本季 / 去年同季),YTD 就是它自己
 *  · Q2/Q3 报告:利润表**四列**(三个月 ×2 + N 个月 ×2),YTD 是第 3 列
 *  · Q4(年报):利润表两列(本年 / 去年),YTD 就是全年
 * 现金流量表三种都只有 YTD 两列(本期 / 去年同期),取第 1 个。
 *
 * ⚠️ 利润表每列占**两个单元格**(金额 + 占营收 %),所以第 c 列的金额在第 2c 个数字上。
 * 这一条踩过:按列号直接索引会取到「去年同季」那一列(实测 Q2 2025 取成 673.5B 而非 1773.0B)。
 */
export function parseTsmcReport(html: string): TsmcYtd {
  const txt = flattenHtml(html);

  // 有「Six/Nine Months Ended」表头 = 期中报告(四列);否则 Q1 或年报(两列)。
  const interim = /For the (Six|Nine) Months Ended/i.test(txt);
  const ytdCell = interim ? 4 : 0; // 第 3 列 → 2*2

  const rev = numsAfter(txt, 'NET REVENUE', ytdCell + 1);
  const cogs = numsAfter(txt, 'COST OF REVENUE', ytdCell + 1);
  const ocf = numsAfter(txt, 'Net cash generated by operating activities', 1);

  // 购置 PP&E 必须锚在「INVESTING ACTIVITIES」之后 —— 处置段里有同名的一行,
  // 而资产负债表/附注里「Property, plant and equipment」出现得更早。
  const invIdx = txt.indexOf('INVESTING ACTIVITIES');
  const capex = invIdx < 0 ? [] : numsAfter(txt, 'Property, plant and equipment', 1, invIdx);

  const pick = (xs: number[], idx: number, what: string): number => {
    const v = xs[idx];
    if (v === undefined || !Number.isFinite(v)) throw new Error(`TSM 合并报表:${what} 没解析出来(列结构可能变了)`);
    return v;
  };

  return {
    revenue: pick(rev, ytdCell, 'NET REVENUE'),
    cogs: pick(cogs, ytdCell, 'COST OF REVENUE'),
    ocf: pick(ocf, 0, '经营活动现金流'),
    capex: Math.abs(pick(capex, 0, '购置不动产厂房设备')), // 报表里是负数(现金流出),存正值
  };
}

// ── CompanyFacts 合成 ─────────────────────────────────────────────────────────

/**
 * 借用 us-gaap 的 tag 名,让这些行能走 extractFundamentals 那条链。
 * **不是说 TSM 报的是 us-gaap** —— 它是 IFRS。这里只是复用下游的科目映射,
 * 落库后 `tag_used` 会显示这几个名字,溯源要看同行的 accn(指向那份 6-K)。
 */
const AS_TAG = {
  revenue: 'Revenues',
  cogs: 'CostOfRevenue',
  ocf: 'NetCashProvidedByUsedInOperatingActivities',
  capex: 'PaymentsToAcquirePropertyPlantAndEquipment',
} as const;

/** 累计期的起点 = 当年 1 月 1 日(TSM 财年 = 日历年)。差分靠「同 start 分组」,故必须一致。 */
const yearStart = (periodEnd: string) => `${periodEnd.slice(0, 4)}-01-01`;

/**
 * 报表原文是**千元**新台币("In Thousands of New Taiwan Dollars"),而下游 deriveSeries 除以
 * 1e6 是按「基础货币单位」算的(companyfacts 给的是元)。不乘这 1000,轴会标着「百万新台币」
 * 而实际是十亿 —— 差三个数量级。踩过一次:FCF TTM 显示 1056 而真值是 1,056,000 百万。
 */
const THOUSANDS_TO_UNITS = 1000;

export function toCompanyFacts(rows: Array<{ filing: FsFiling; ytd: TsmcYtd }>): CompanyFacts {
  const entries = Object.entries(AS_TAG).map(([concept, tag]) => {
    const usd: FactRow[] = rows.map(({ filing, ytd }) => ({
      start: yearStart(filing.periodEnd),
      end: filing.periodEnd,
      val: ytd[concept as keyof TsmcYtd] * THOUSANDS_TO_UNITS,
      accn: filing.accn,
      // 6-K 不是定期报告,而 periodsForTag 只收 10-Q/10-K —— 标成 10-Q 让它进得去。
      // 这是**刻意的伪装**:TSM 的季报在功能上等同 10-Q,只是外国发行人用 6-K 交。
      form: '10-Q',
      filed: filing.filed,
    }));

    return [tag, { units: { USD: usd } }] as const;
  });

  return { facts: { 'us-gaap': Object.fromEntries(entries) } };
}

// ── 抓取 ──────────────────────────────────────────────────────────────────────

export function createTsmcFetcher(doFetch: FetchFn = fetchWithTimeout) {
  return {
    /** 全部季度财报 6-K,按期末升序。primaryDocument 以 `tsm-fs` 开头是它们的稳定标志。 */
    async listFsFilings(cik: string): Promise<FsFiling[]> {
      const body = (await (
        await get(`https://data.sec.gov/submissions/CIK${cik.padStart(10, '0')}.json`, doFetch)
      ).json()) as Submissions;
      const {
        form = [],
        filingDate = [],
        reportDate = [],
        accessionNumber = [],
        primaryDocument = [],
      } = body.filings?.recent ?? {};

      return primaryDocument
        .flatMap((doc, i) =>
          form[i] === '6-K' && /^tsm-fs/i.test(doc ?? '') && reportDate[i] && accessionNumber[i] && filingDate[i]
            ? [{ accn: accessionNumber[i]!, filed: filingDate[i]!, periodEnd: reportDate[i]! }]
            : [],
        )
        .sort((a, b) => a.periodEnd.localeCompare(b.periodEnd));
    },

    /**
     * 取某份 6-K 里的合并报表正文。
     *
     * **不按文件名认**:命名不稳定(实测出现过 `tsmc2023q1.htm`、`a0515.htm`、拼错的
     * `consolidatd`、以及 workiva 前缀)。改成「排除 6-K 封面与母公司单独报表后取最大那份」——
     * 合并报表 4MB 级,封面十几 KB,量级差三个数量级。
     */
    async fetchReport(cik: string, accn: string): Promise<string> {
      const dir = `${ARCHIVES}/${Number(cik)}/${accn.replace(/-/g, '')}`;
      const idx = (await (await get(`${dir}/index.json`, doFetch)).json()) as DirIndex;

      const doc = (idx.directory?.item ?? [])
        .filter(
          (i) =>
            /\.htm$/i.test(i.name ?? '') &&
            !/^tsm-fs/i.test(i.name ?? '') &&
            !/index/i.test(i.name ?? '') &&
            !/standalone|uncons/i.test(i.name ?? ''),
        )
        .sort((a, b) => Number(b.size ?? 0) - Number(a.size ?? 0))[0];
      if (!doc?.name) throw new Error(`TSM 6-K ${accn}: 目录里没有合并报表正文`);

      return (await get(`${dir}/${doc.name}`, doFetch, REPORT_TIMEOUT_MS)).text();
    },
  };
}
